let products = [
    {
  id:1,
  model:"Samsung A8s",
  price:"750",
  currently:"£",
  photo:"maxresdefault_large.jpg",
  description:"Samsung Galaxy A8s, первый смартфон компании с отверстием в экране,обновили до Android 9 Pie,",

},
{
    id:2,
    model:"Samsung Galaxy A30",
    price:"870",
    currently:"£",
    photo:"samsung-galaxy-a30s-mini@2x.jpeg",
    description:"Samsung Galaxy A30 64GB 4GB RAM Dual SIM 4G LTE Black",
  },
  {
    id:3,
    model:"Samsung Galaxy S10 5G",
    price:"1250",
    currently:"£",
    photo:"61riXOZAl5L._AC_SX569_.jpg",
    description:"The Samsung Galaxy S10 5G is an amazing 5G phone with a beautiful 6.7 inch WQHD screen and 4500 mAh battery. ",
  },
  {
      id:4,
      model:"Смартфон Samsung Galaxy A5",
      price:"250",
      currently:"£",
      photo:"samsung-galaxy-a5-mini@2x.jpeg",
      description:"Смартфон Samsung Galaxy A5 (2016) SM-A510F ",
  },
      {
        id:5,
        model:"Samsung Galaxy S9 Dual",
        price:"920",
        currently:"£",
        photo:"Samsung-Galaxy-S9-64GB-Coral-Blue-27022018-04-p.jpg",
        description:" Samsung Galaxy S9 Dual SIM - 64GB, 4GB RAM, Octa-core, IP68, 12 MP, Android 8.0, 5.8 Super AMOLED, 3000mAh Open Box - Excellent: The seal is broken .. ",
      },
      {
          id:6,
          model:"Samsung Galaxy A70",
          price:"960",
          currently:"£",
          photo:"New-Samsung-Galaxy-A70-A7050-Mobile-Phone-6-7-8GB-RAM-128GB-ROM-Snapdragon-675-Octa.webp",
          description:"Samsung Galaxy A70 (A705F), Coral",
      },
      {
        id:7,
        model:"2 Android Phone",
        price:"750",
        currently:"£",
        photo:"ROG1.5_large.jpg",
        description:"BODY, 143.5 x 71.3 x 9.3 mm (5.65 x 2.81 x 0.37 in) - Plastic front, aluminum frame, polycarbonate back Single SIM (Nano-SIM) or Dual SIM ",
      },
      {
          id:8,
          model:"Google Pixel Phone",
          price:"850",
          currently:"£",
          photo:"download.jpg",
          description:" Google Pixel Phone 128 GB - 5 inch display ( Factory Unlocked US Version ) (Very Silver)",
        },
        {
          id:9,
          model:"Iphone-9",
          price:"1250",
          currently:"£",
          photo:"43423_large.jpg",
          description:"The Iphone-9 5G is an amazing 5G phone with a beautiful 6.7 inch WQHD screen and 4500 mAh battery. ",
        },
        {
            id:10,
            model:"golden MacOs",
            price:"75 655 545",
            currently:"£",
            photo:"download (1).jpg",
            description:"gold gold gold gold gold only gold",
        },
            {
              id:11,
              model:"diamond iphone-X",
              price:"48 649 579",
              currently:"£",
              photo:"24ct-Gold-iPhone-X-Diamond-Marina-Edition-3.jpg",
              description:" Samsung Galaxy S9 Dual SIM - 64GB, 4GB RAM, Octa-core, IP68, 12 MP, Android 8.0, 5.8 Super AMOLED, 3000mAh Open Box - Excellent: The seal is broken .. ",
            },
            {
                id:12,
                model:"Iphone-6",
                price:"920",
                currently:"£",
                photo:"download (2).jpg",
                description:"Samsung Galaxy A70 (A705F), Coral",
            },
            {
              id:13,
              model:"IPhone-8s",
              price:"720",
              currently:"£",
              photo:"9hq.webp",
              description:"IPhone-8s, первый смартфон компании с отверстием в экране, обновили до Android 9 Pie,",
            },
            {
                id:14,
                model:"IPhone 7",
                price:"780",
                currently:"£",
                photo:"74fcdc2192a2443ef3c23a7e1fd3c10b.jpg",
                description:"IPhone 7 64GB 4GB RAM Dual SIM 4G LTE Black",
              },
              {
                id:15,
                model:"The Iphone X 5G",
                price:"1120",
                currently:"£",
                photo:"samsung-galaxy-a5-mini@2x.jpeg.",
                description:"The Iphone X 5G is an amazing 5G phone with a beautiful 6.7 inch WQHD screen and 4500 mAh battery. ",
              },
              {
                  id:16,
                  model:"Смартфон IPhone 5 ",
                  price:"210",
                  currently:"£",
                  photo:"download (3).jpg",
                  description:"Смартфон IPhone 5 (2016) ip-510F ",
              },
                  {
                    id:17,
                    model:"Iphone 11",
                    price:"1210",
                    currently:"£",
                    photo:"f8a14c9441350b92c4e97dba03fd08f9.jpg",
                    description:" Iphone 11 SIM - 64GB, 4GB RAM, Octa-core, IP68, 12 MP, Android 8.0, 5.8 Super AMOLED, 3000mAh Open Box - Excellent: The seal is broken .. ",
                  },
                  {
                      id:18,
                      model:"Samsung Galaxy A30",
                      price:"810",
                      currently:"£",
                      photo:"frntblk-1200x1200.jpg",
                      description:"Samsung Galaxy A30 (A305F), Coral",
                  }

];